ALTER TYPE "StudentStatus" ADD VALUE IF NOT EXISTS 'PAUSADO';
ALTER TYPE "StudentStatus" ADD VALUE IF NOT EXISTS 'DESACTIVADO';

ALTER TYPE "MonthlyPaymentStatus" ADD VALUE IF NOT EXISTS 'NO_APLICA';

ALTER TABLE "students"
ADD COLUMN IF NOT EXISTS "fechaInicioPausa" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "fechaFinPausa" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "motivoEstado" TEXT;
